name: Fork PR Test

on:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Basic test
        run: echo \"PR workflow running\"
      - name: Print env
        run: env | sort
